apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lng-trading-app
spec:
  build:
    useBuildKit: true
  environments:
    - name: dev
      build:
        from: main
    - name: prod
      build:
        from: release
  components:
    - name: backend
      src: "."
      dockerfileName: backend/Dockerfile
      ports:
        - name: http
          port: 8000
      secrets:
        - SECRET_KEY
        - DATABRICKS_SERVER_HOSTNAME
        - DATABRICKS_HTTP_PATH
        - DATABRICKS_TENANT_ID
        - DATABRICKS_CLIENT_ID
        - DATABRICKS_CLIENT_SECRET
        - DATABRICKS_WORKSPACE_RESOURCE_ID
        - GRAPH_TENANT_ID
        - GRAPH_CLIENT_ID
        - GRAPH_CLIENT_SECRET
      variables:
        NEWS_BACKEND: databricks
        NEWS_TABLE: ms_vulcan_gplng_plab.lng_apac.platts_lng_top_news
        DATABRICKS_USE_SERVICE_PRINCIPAL: "true"
        FIRST_SUPERUSER: admin@example.com
        GRAPH_MAIL_FROM: csee@equinor.com
      healthChecks:
        livenessProbe:
          httpGet:
            port: 8000
            path: /api/v1/utils/health-check
          initialDelaySeconds: 20
          periodSeconds: 20
        readinessProbe:
          httpGet:
            port: 8000
            path: /api/v1/utils/health-check
          initialDelaySeconds: 10
          periodSeconds: 10

    - name: frontend
      src: "."
      dockerfileName: frontend/Dockerfile
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: dev
          variables:
            VITE_BYPASS_AUTH: "true"
        - environment: prod
          variables:
            VITE_BYPASS_AUTH: "false"
