/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutNewsletterRouteImport } from './routes/_layout/newsletter'
import { Route as LayoutNews_summary_condensedRouteImport } from './routes/_layout/news_summary_condensed'
import { Route as LayoutNews_summaryRouteImport } from './routes/_layout/news_summary'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNewsletterRoute = LayoutNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNews_summary_condensedRoute =
  LayoutNews_summary_condensedRouteImport.update({
    id: '/news_summary_condensed',
    path: '/news_summary_condensed',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNews_summaryRoute = LayoutNews_summaryRouteImport.update({
  id: '/news_summary',
  path: '/news_summary',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/news_summary': typeof LayoutNews_summaryRoute
  '/news_summary_condensed': typeof LayoutNews_summary_condensedRoute
  '/newsletter': typeof LayoutNewsletterRoute
}
export interface FileRoutesByTo {
  '/news_summary': typeof LayoutNews_summaryRoute
  '/news_summary_condensed': typeof LayoutNews_summary_condensedRoute
  '/newsletter': typeof LayoutNewsletterRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/news_summary': typeof LayoutNews_summaryRoute
  '/_layout/news_summary_condensed': typeof LayoutNews_summary_condensedRoute
  '/_layout/newsletter': typeof LayoutNewsletterRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/news_summary' | '/news_summary_condensed' | '/newsletter'
  fileRoutesByTo: FileRoutesByTo
  to: '/news_summary' | '/news_summary_condensed' | '/newsletter' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/news_summary'
    | '/_layout/news_summary_condensed'
    | '/_layout/newsletter'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/newsletter': {
      id: '/_layout/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof LayoutNewsletterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/news_summary_condensed': {
      id: '/_layout/news_summary_condensed'
      path: '/news_summary_condensed'
      fullPath: '/news_summary_condensed'
      preLoaderRoute: typeof LayoutNews_summary_condensedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/news_summary': {
      id: '/_layout/news_summary'
      path: '/news_summary'
      fullPath: '/news_summary'
      preLoaderRoute: typeof LayoutNews_summaryRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutNews_summaryRoute: typeof LayoutNews_summaryRoute
  LayoutNews_summary_condensedRoute: typeof LayoutNews_summary_condensedRoute
  LayoutNewsletterRoute: typeof LayoutNewsletterRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutNews_summaryRoute: LayoutNews_summaryRoute,
  LayoutNews_summary_condensedRoute: LayoutNews_summary_condensedRoute,
  LayoutNewsletterRoute: LayoutNewsletterRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
